### ISSUE TITLE
Changing the map is really difficult

### ISSUE THREAD

**Issue by ScribbleTAS** [MGW14/FFA#6]
## What you have to do:  
Normally you get into worldedit and select the area, tp to 0 0 0 type //copy and //schem save <name>

## Issues:
When you are using mcedit the origin seems to be all over the place... Plus if a map is smaller than the old one parts of the old map don't get overwritten... And the spawn platform may get overridden

## Solution:
Multiple configs for multiple maps... Copy the enire map plus spawn platform and keep the chest with the items away from the schematic... Maybe we try and serialize the items 😣

Quantees attempt at changing the map:
![2020-11-16_10 01 19](https://user-images.githubusercontent.com/28013575/99266306-e9b6c300-2822-11eb-8d95-8f6d8102d785.png)

**Comment by Quanteey** [comment]
Also, put the schematics 0/0/0 at the world 0/0/0, so there's no need to mess around with map offsets

**Comment by ScribbleTAS** [comment]
@Quantum155 In this case we need to move the desert map to 0 0 0 then

**Comment by MGW14** [comment]
This Issue has (kinda) been fixed (but still doesn't work for other reasons).
